version: "3.9"

services:
  client:
    volumes:
      - ./client:/usr/share/nginx/html

  server:
    build:
      target: dev
    volumes:
      - ./server:/app
    environment:
      - MAIL_HOST=mailcatcher
      - MAIL_PORT=1025
    depends_on:
      - mailcatcher

  admin:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - database
    networks:
      - app-network

  mailcatcher:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    networks:
      - app-network